// Parts catalog: types and access. Data comes from data/parts.json (generated by tools/build_catalog.py).
// Every part has sockets only; parts are joined with a loose snap pin - horizontally at every joint, vertically
// between part and adapter and within adapter towers.
import partsJson from './data/parts.json';

export type Vec3 = [number, number, number];
/** Horizontal socket: point on the end face (socket mouth, z 5.7 above the base), normal pointing out of the part. */
export interface Port { p: Vec3; n: Vec3 }
/** Vertical socket: centre (x, y), socket width axis and side of the collar ears (flat side of the D profile).
 *  The snap pin has a D profile - two sockets only mate if all three values match. */
export interface VSock { c: [number, number]; wax: 'x' | 'y'; ear: number }
/** Adapter under a part: type, position in part coordinates and rotation (mirrored curves: standard adapter at -90°). */
export interface AdapterSpec { type: string; offset: [number, number]; rot: number }
export interface Limits { vmin?: number; vmax?: number; vwarn?: number; why?: string; whyEn?: string }
export interface Phys {
  k: number; L: number | null; drop: number; limits: Limits; R?: number;
  crest?: { dh: number; R: number; vcrestMax: number };
  loss?: number; brake?: { threshold: number; cap: number; runout?: number };
  fixedExit?: number; estimate?: boolean; v0?: number;
  inLoss?: number;   // Y merge: factor applied to the entry speed (loss at the junction, from 3D simulation)
}
export type Family = 'start' | 'end' | 'straight' | 'curve' | 'longCurve' | 'spacer' | 'levelChanger' | 'lift' | 'brake' | 'attraction' | 'adapter' | 'pin' | 'liftPart' | 'flipflopPart';
export type System = 'channel' | 'rail' | 'tunnel' | 'adapter' | 'pin';

/** Screw lift: a single chain part (family lift) built from modules (family liftPart) - base, N-1 middle sections,
 *  head, one screw segment per module, crank. BOM, print plates and 3MF use the modules (kit); the 3D view assembles
 *  them (asm: module, height, rotation about the lift axis). */
export interface LiftSpec {
  n: number;                                       // levels the lift raises (exit at level n)
  dir: 'straight' | 'left' | 'back' | 'right';  // exit direction relative to the entry
  headRot: number;                                 // head rotation (degrees, counter-clockwise)
  kit: { id: string; n: number }[];                // modules for BOM and printing
  pins: number;                                    // snap pins in the lift (between modules + crank)
  asm: { id: string; z: number; rot: number }[];   // assembly for the 3D view
  crankR: number; housingTop: number; crankZ: [number, number];
}

/** Kit part (flip-flop): one chain part made of several printed parts. kit: printed parts for BOM and printing;
 *  asm: assembly for the 3D view (module, height, rotation). The lift stores both in `lift` (kitOf/asmOf read both). */
export interface KitItem { id: string; n: number }
export interface AsmItem { id: string; z: number; rot: number }

export interface Part {
  id: string; code: string; file: string; family: Family; system: System; mirrored: boolean;
  rimIn: number | null; rimOut: number | null; feedRim: number | null;   // rim codes as in the part name (40/50/60/100/120/180)
  bbox: [Vec3, Vec3]; foot: [number, number, number, number]; height: number;
  volume: number; area: number; grams: number; hours: number;
  ports: Port[];
  lane: [number | null, number | null];            // lane: indices of the entry/exit socket in ports
  reversible: boolean;
  vsock: { bottom: VSock[]; top: VSock[] };         // vertical sockets, measured on the STL
  phys: Phys;
  turn: number; radius: number | null; center: [number, number] | null; length: number | null;
  adapter: AdapterSpec | null; note: string; noteEn?: string;
  nameEn: string;                                  // English part name
  released: boolean;                               // in the main print profile (not under "Extras")
  plate: { no: number; name: string } | null;      // plate in the print profile (each part exactly once)
  printRot: number;                                // print orientation in the profile (rotation about z)
  printMeta: Record<string, string>;               // per-object profile settings (e.g. curves 45°, adapters 10 %)
  jp: { grams: number; hours: number } | null;   // Japandi edition: grooved (own meshes, weight, time); null = same as plain
  legacy?: boolean;
  lift?: LiftSpec;                                 // family lift only
  palette?: boolean;                               // false: not in the palette (lift with rotated head - via "rotate exit")
  src?: string; srcJ?: string;                     // STL outside the CAD export (lift modules), pipeline only
  kit?: KitItem[]; asm?: AsmItem[];                // kit part without its own mesh (flip-flop): printed parts and 3D assembly
  floorOnly?: boolean;                             // floor only (level 0) - no adapter, does not hang on neighbors
  swap?: string;                                   // counterpart in the detail panel (flip-flop: "switch exit")
  display?: boolean;                               // 3D view only (built-in rocker), never in BOM or print
  lanes?: [number, number][];                      // multi-lane part (Y merge): [entry, exit] per lane
  merge?: boolean;                                 // merge: the lanes share one exit (Y merge)
}

export interface Catalog { parts: Part[]; byId: Map<string, Part>; calib: { g: number[]; h: number[]; plateH: number } }

const data = partsJson as unknown as { parts: Part[]; calib: { g: number[]; h: number[]; plateH: number } };
export const catalog: Catalog = {
  parts: data.parts,
  byId: new Map(data.parts.map((p) => [p.id, p])),
  calib: data.calib,
};

/** System dimensions: level height (mm), socket centre above the base (mm), rim code -> mm factor. */
export const LEVEL = 32;
export const PORT_Z = 5.7;
export const SCALE = 8 / 15;
/** The snap pin - one per joint, per tower level and per adapter coupling. */
export const SNAP_PIN = 'Raststift_16mm';
/** Shorter parts hang on their neighbors (spacers, Gerade88). */
export const HANG_MAX = 48;

/** Rim height in mm for a rim code (40 -> 21.333; level changer 100 -> 53.333). */
export function rimMm(code: number): number { return code * SCALE; }
/** Height of the ball centre above the base: rim - groove depth 8.75 + ball radius 8. */
export function ballZ(code: number): number { return rimMm(code) - 0.75; }

/** Does the part need an adapter above level 0 (instead of hanging on its joints)? Short parts hang on their
 *  neighbors; longer parts without an adapter mapping (end bowl, spiral, X crossing, loops - there are no pedestals)
 *  can only stand on level 0. */
export function needsAdapter(p: Part): boolean {
  if (p.floorOnly) return true;
  if (p.adapter || ['adapter', 'pin', 'spacer'].includes(p.family)) return false;
  return p.foot[2] - p.foot[0] > HANG_MAX;
}

/** Edition: plain or Japandi (vertical grooves on the flat side walls). Geometry, sockets, plates and physics are
 *  identical; meshes, weight/print time, print profile and app styling differ. */
export type Edition = 'plain' | 'japandi';
let edition: Edition = 'plain';
export function setEdition(e: Edition) { edition = e; }
export function getEdition(): Edition { return edition; }
export function isJapandi(): boolean { return edition === 'japandi'; }
/** Does the part have its own (grooved) meshes in the Japandi edition? */
export function grooved(p: Part): boolean { return !!p.jp; }
/** Filament weight and print time in the active edition. */
export function partGrams(p: Part): number { return edition === 'japandi' && p.jp ? p.jp.grams : p.grams; }
export function partHours(p: Part): number { return edition === 'japandi' && p.jp ? p.jp.hours : p.hours; }

export function part(id: string): Part {
  const p = catalog.byId.get(id);
  if (!p) throw new Error('Unknown part: ' + id);
  return p;
}

/** Parts with two lanes (X crossing): [entry, exit] port indices per lane in forward direction (high rim -> low rim;
 *  measured on the STL: channel floor at -y and -x 18.8 mm, at +y and +x 14.5 mm). The chain uses one lane
 *  (ChainElement.lane, default 0); the other is free: other strands pass through it or continue from its exit. */
export const LANES: Record<string, [number, number][]> = {
  'XKreuzung_50-40_16mm': [[0, 1], [3, 2]],
};
/** Free exits for a branch (second strand) per part, as port indices. Flip-flop: the other exit (every second ball). */
export const BRANCH_PORTS: Record<string, number[]> = {
  'Kippwippe_120-60_Links_16mm': [3], 'Kippwippe_120-60_Rechts_16mm': [3],
};
/** Merge parts (Y merge): two lanes sharing one exit (catalog fields lanes, merge). The chain uses one lane
 *  (direction = which entry); another strand ends in the other entry (chain.ts laneDock). No branch: the exit belongs to the chain. */
export const MERGE = new Set<string>();
for (const p of data.parts) if (p.lanes) { LANES[p.id] = p.lanes; if (p.merge) MERGE.add(p.id); }
export function isMerge(p: Part): boolean { return MERGE.has(p.id); }
/** Lane of a part (entry/exit port indices, forward); lane selects the lane on multi-lane parts. */
export function laneOf(p: Part, lane = 0): [number | null, number | null] {
  const l = LANES[p.id];
  return l ? l[lane] ?? l[0] : p.lane;
}
/** The free lane of a multi-lane part when the chain uses `lane`; otherwise null. */
export function freeLane(p: Part, lane = 0): [number, number] | null {
  const l = LANES[p.id];
  if (!l || l.length < 2) return null;
  return l[lane === 1 ? 0 : 1];
}
/** Exits where a branch can start: flip-flop second exit, X crossing exit of the free lane
 *  (Y merge: none - both lanes end in the same exit). */
export function branchPorts(p: Part, lane = 0): number[] {
  const fl = freeLane(p, lane);
  return [...(BRANCH_PORTS[p.id] ?? []), ...(fl && !MERGE.has(p.id) ? [fl[1]] : [])];
}
/** Rim code (relative to the part's own base) at a socket: entry = rimIn, exit = rimOut (forward, per lane). */
export function portRim(p: Part, port: number): number | null {
  const lanes = LANES[p.id] ?? [p.lane];
  for (const l of lanes) { if (l[0] === port) return p.rimIn; if (l[1] === port) return p.rimOut; }
  if ((BRANCH_PORTS[p.id] ?? []).includes(port)) return p.rimOut;
  return null;
}

/** Entry/exit socket of a part in chain direction; swapped when reversed (all ends are sockets).
 *  lane: X crossing lane (0 = -y -> +y, 1 = -x -> +x). */
export function entryExit(p: Part, reversed: boolean, lane = 0): { entry: Port | null; exit: Port | null } {
  const ln = laneOf(p, lane);
  const a = ln[0] != null ? p.ports[ln[0]] : null;
  const b = ln[1] != null ? p.ports[ln[1]] : null;
  return reversed && p.reversible ? { entry: b, exit: a } : { entry: a, exit: b };
}
/** Entry/exit port indices in chain direction. */
export function entryExitIdx(p: Part, reversed: boolean, lane = 0): [number | null, number | null] {
  const ln = laneOf(p, lane);
  return reversed && p.reversible ? [ln[1], ln[0]] : [ln[0], ln[1]];
}

/** Rim the preceding part must deliver for this part to fit (in chain direction). */
export function requiredFeedRim(p: Part, reversed: boolean): number | null {
  if (p.feedRim == null) return null;
  if (reversed && p.reversible) return p.rimOut; // reversed: only parts with both sockets at standard height
  return p.feedRim;
}

/** Flat curve (same rim, 90°): reversed it becomes the opposite curve, so there are no mirrored flat curves. */
export function isFlatCurve(p: Part): boolean {
  return (p.turn === 90 || p.turn === -90) && p.rimIn != null && p.rimIn === p.rimOut && p.reversible;
}

export const FAMILY_ORDER: Family[] = ['start', 'straight', 'curve', 'longCurve', 'spacer', 'levelChanger', 'lift', 'attraction', 'brake', 'end', 'adapter', 'pin', 'liftPart', 'flipflopPart'];

/** Printed parts of a chain part (lift modules; flip-flop: body, rocker, axle pin); null: the part itself is printed. */
export function kitOf(p: Part): KitItem[] | null { return p.lift?.kit ?? p.kit ?? null; }
/** Assembly for the 3D view (lift, flip-flop); null: the part's own mesh. */
export function asmOf(p: Part): AsmItem[] | null { return p.lift?.asm ?? p.asm ?? null; }

/** Tallest lift in the catalog (levels) and the height above which lifts are computed only (not built/printed). */
export const LIFT_MAX = Math.max(0, ...catalog.parts.filter((p) => p.lift).map((p) => p.lift!.n));
export const LIFT_TESTED = 5;
/** Lift variant with another height or head direction (null if none exists). */
export function liftVariant(p: Part, n: number, dir: LiftSpec['dir']): Part | null {
  if (!p.lift) return null;
  const want = (q: Part) => !!q.lift && q.lift.n === n && q.lift.dir === dir;
  return catalog.parts.find(want) ?? null;
}
/** Next head direction: straight -> left -> back -> right -> straight (head +90°). */
export const LIFT_DIRS: LiftSpec['dir'][] = ['straight', 'left', 'back', 'right'];
export function nextLiftDir(d: LiftSpec['dir']): LiftSpec['dir'] { return LIFT_DIRS[(LIFT_DIRS.indexOf(d) + 1) % LIFT_DIRS.length]; }
